# Generated by Django 5.1.3 on 2024-12-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateneu', '0002_remove_customuser_senha_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nome_completo',
            field=models.CharField(default='Nome não informado', max_length=255, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
    ]
